apiVersion: apps/v1

kind: Deployment

metadata:

  name: pgadmin

  labels:

    app: pgadmin

    tier: frontoback

spec:

  replicas: 1

  selector:

    matchLabels:

      app: pgadmin

      tier: frontoback

  template:

    metadata:

      labels:

        app: pgadmin
        
        tier: frontoback
        
    spec:

      containers:

      - name: pgadmin

        image: dpage/pgadmin4

        ports:

        - containerPort: 80

        env:

          - name: PGADMIN_DEFAULT_EMAIL
            
            value: bbio@duck.com
          
          - name: PGADMIN_DEFAULT_PASSWORD
          
            value: secret

        volumeMounts:

          - name: servers-json

            mountPath: /pgadmin4/servers.json

          - name: pgadmin-data

            mountPath: /var/lib/pgadmin

      volumes:

        - name: pgadmin-data

          hostPath:

            path: pgadmin-data-dossier

        - name: servers-json

          hostPath:

            path: servers.json



            


