apiVersion: apps/v1

kind: Deployment

metadata:

  name: ic-webapp

  labels:

    app: ihm

    tier: frontend

spec:

  replicas: 1

  selector:

    matchLabels:

      app: ihm

      tier: frontend

  template:

    metadata:

      labels:

        app: ihm

        tier: frontend
        
    spec:

      containers:

      - name: ic-webapp

        image: biobern/ic-webapp:v1.0

        ports:

        - containerPort: 8080

        env:
          - name: ODOO_URL
            
            value: http://192.168.49.2:30009
          
          - name: PGADMIN_URL
          
            value: http://192.168.49.2:30010



