apiVersion: apps/v1

kind: Deployment

metadata:

  name: postgres-odoo

  labels:

    app: postgres-odoo
      
    tier: backend

spec:

  replicas: 1

  selector:

    matchLabels:

      app: postgres-odoo

      tier: backend

  template:

    metadata:

      labels:

        app: postgres-odoo

        tier: backend
        
    spec:

      containers:

      - name: postgres-odoo

        image: postgres

        env:
          
          - name: POSTGRES_PASSWORD
            
            value: secret
          
          - name: POSTGRES_DB
          
            value: postgres

          - name: POSTGRES_USER

            value: alice

        volumeMounts:

          - name: odoo-db-data
            
            mountPath: /var/lib/postgresql/data
           
      volumes:

        - name: odoo-db-data

          hostPath:

            path: odoo_db_dossier

