apiVersion: v1

kind: Service

metadata:

  name: odoo

spec:

  type: NodePort

  selector:

    app: odoo

    tier: frontend

  ports:

    - targetPort: 8069   

      port: 8069

      nodePort: 30009
