apiVersion: v1

kind: Service

metadata:

  name: service-web

spec:

  type: NodePort

  selector:

    app: ihm
    tier: frontend

  ports:

    - targetPort: 8080   

      port: 8080

      nodePort: 30008
