apiVersion: v1

kind: Service

metadata:

  labels:

    app: pgadmin

    tier: frontoback

  name: pgadmin

spec:

  selector:

    app: pgadmin

    tier: frontoback

  type: NodePort

  ports:
    
    - nodePort: 30010 

      port: 80

      targetPort: 80
