apiVersion: v1

kind: Service

metadata:

  labels:

    app: postgres-odoo

    tier: backend

  name: postgres-odoo

spec:

  selector:

    app: postgres-odoo

    tier: backend

  type: ClusterIP

  ports:
    
    - protocol: TCP

      port: 5432

      targetPort: 5432
